CREATE TABLE ORDER_DETAILS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  orderName VARCHAR(250) NOT NULL,
  totalAmount VARCHAR(250) NOT NULL
);


CREATE TABLE CUSTOMER_ACCOUNT (
  custId VARCHAR(250) PRIMARY KEY,
  CustName VARCHAR(250) NOT NULL,
  custPhone VARCHAR(250) NOT NULL
);


CREATE TABLE LISTOF_ORDERS (
  orderId INT AUTO_INCREMENT  PRIMARY KEY,
  itemName VARCHAR(250) NOT NULL,
  date VARCHAR(250) NOT NULL,
  accId  VARCHAR(250) NOT NULL
);